#gcc hellowebcam.c -I/usr/local/Cellar/opencv/2.3.1a/include/opencv -lopencv_highgui -lopencv_core

CFLAGS = -g -Wall -I/usr/local/Cellar/opencv/2.3.1a/include/opencv -lopencv_highgui -lopencv_core
CXXFLAGS = $(CFLAGS)

all: hellowebcam
